### ISSUE TITLE
Custom Geometry

### ISSUE THREAD

**Issue by QuiverlyRivalry** [jojoe77777/Slapper#102]
Using PMMP using custom geometric skins. It makes them flat instead of making it look. The same

**Comment by 95CivicSi** [comment]
@QuiverlyRivalry I looked at this today and was able to recreate it.  Here's a demonstration using "Dust An Elysian Tail Party Fidget" skin from the Legacy Skin Pack.  Custom Geometry is the party hat.

https://youtu.be/ZU7sRadDYoA

**Comment by QuiverlyRivalry** [comment]
How would we fix i?

**Comment by 95CivicSi** [comment]
I'm not really familiar with how skins and geometry are handled in PMMP period so I need some time to look through the code and get familiar with it's methods.

**Comment by 95CivicSi** [comment]
There are 2 problems.  First is in PMMP.  Non-Player Human entities do not have a method for saving geometry and cape data to NBT yet.

https://github.com/pmmp/PocketMine-MP/blob/45ee115b67836bb320b326cde62da11d0b8844ed/src/pocketmine/entity/Human.php#L518-L524

Second problem is Slapper not pulling skin geometry or cape data from the user because PMMP doesn't define how to save it yet.

https://github.com/jojoe77777/Slapper/blob/35f9fe6236cfd2f0c9597fbd742ea5c0d648b3b3/src/slapper/Main.php#L676

Not sure if this should be fixed yet.  It would be possible to work around this problem until PMMP updates this method but it would be hacky.  NBT skin saves would have to be handled in SlapperHuman.

**Comment by dktapps** [comment]
This should now work as expected with latest development builds.
