### ISSUE TITLE
Why tesseract is not supported?

### ISSUE THREAD

**Issue by poustmal** [jojoe77777/Slapper#41]
Why is not supported?Its stable software,many features than pocketmine a bit and is not dead yet.

**Comment by poustmal** [comment]
And I saw some comments in another issues.Make a different branch for tesseract.

**Comment by Sandertv** [comment]
Because it is not supported. Tesseract is a highly unstable copy-pasting spoon of PocketMine with changes to the API which are not compatible with Slapper. Labeling something as 'stable' doesn't mean it is. If you want to use Slapper, use PocketMine. Not supported means not supported. Deal with it :nerd_face:

**Comment by dktapps** [comment]
Because we don't like wasting our time trying to work with other people's stupidity.

**Comment by poustmal** [comment]
....

**Comment by poustmal** [comment]
Pocketmine is stable only because is very active software and original idk,but it has more issues/bugs and more unsupported items.

**Comment by dktapps** [comment]
We're not supporting Tesseract because we don't _want_ to support it. Got it yet? We do not encourage using spoons, and we will not make efforts for those who wish to waste their time on spoons.

**Comment by dktapps** [comment]
Also, less issues != less bugs. Less issues in the case of spoon usually means less _reported_ bugs, or more incorrectly closed issues.

**Comment by poustmal** [comment]
I have already got it,but is a bit disappointing and no other comments now.
